config/routes.rb
GaSchedulerv3::Application.routes.draw do
  

  get "home/index"

  root to: 'home#index'

 

  get "/signup",    to: "profiles#new",      as: :signup
  get "/login",     to: "sessions#new",     as: :login
  delete "/logout", to: "sessions#destroy", as: :logout

  get "/profile", to: "profiles#edit", as: :my_profile

 
  resources :sessions, only: [:new, :create, :destroy]
 
  resources :locations

  resources :histories

  resources :classrooms

  resources :statuses

  resources :profiles

  resources :roles

  resources :tutorials

  resources :cohorts do 
    member do
      get :enroll
    end
  end

  resources :lessons

  resources :courses
 

 

   

end

app/models/ability.rb
class Ability
  include CanCan::Ability
     
  def initialize(user)

    user ||= Profile.new
    case user.role.name
    
      when "admin"
           can :manage, :all
      when "producer"
        can :manage, Cohort
        can [:update, :edit, :index], Profile
        can [:index, :show], Course
       when "instructor"
        can [:edit, :update], Profile
        can :manage, Cohort
       when "student"
        can [:edit, :update], Profile
        can [:index, :show, :enroll], Cohort
        when "teaching assistant"
        can [:edit, :update], Profile
        can :manage, Cohort
      end
    end
  end

#     if user.role.name == "admin"
#       can :manage, :all
#     end

#     if user.role.name == "producer"
#       can :edit, :new, :destory, Cohorts
#     end
#   end
# end
  
  

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :chairs, :chillout, :location_id, :name, :projector, :tables
  
  belongs_to :location
  has_many :tutorials

  validates :name, :location_id, presence: true
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :course_id, :end_date, :location_id, :name, :start_date, :status_id, :profile_ids
  belongs_to :course
  has_many :tutorials
  has_and_belongs_to_many :profiles
  belongs_to :status
  belongs_to :location



  validates :name, presence: true, uniqueness: true
  validates :profile_ids, presence: true
  
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :description, :name, :outcome, :status_id, :lesson_ids

has_and_belongs_to_many :lessons
belongs_to :status


 validates :name, presence: true, uniqueness: true

end

app/models/history.rb
class History < ActiveRecord::Base
  attr_accessible :c_id, :p_id, :st_id, :t_id
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :name, :status_id, :subject, :timerequired
  
  has_and_belongs_to_many :courses
  belongs_to :status

  validates :name, presence: true, uniqueness: true
  validates :subject, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  
  has_many :profiles
  has_many :classrooms
  has_many :tutorials
  has_many :cohorts

   validates :name, presence: true, uniqueness: true

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible  :name, :picture, :location_id, :role_id, :password, :email, :password_confirmation
  
  belongs_to :role
  has_and_belongs_to_many :cohorts
  has_and_belongs_to_many :tutorials
  belongs_to :location
  
  mount_uploader :picture, ProfileImageUploader
  
  has_secure_password
  
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
   has_many :profiles

  validates :name, presence: true, uniqueness: true
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :statusname, :thing

  has_many :courses
  has_many :lessons

 validates :statusname, presence: true, uniqueness: true
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  attr_accessible :cohort_id, :name, :status_id, :subject, :timerquired, :classroom_id, :location_id
    
    belongs_to :cohort
    belongs_to :classroom
    has_and_belongs_to_many :profiles
    belongs_to :status
    belongs_to :location
  
end

app/models/user.rb
class User < ActiveRecord::Base
   has_secure_password
  
  validates :email, presence: true, uniqueness: true
  attr_accessible :email, :password, :password_confirmation, :role
  belongs_to :profile


  def role?(role_to_test)
    self.role.to_s == role_to_test.to_s
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
    before_filter :authenticate
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  

  def admin?     
      current_user && current_user.role.name == "admin"
  end


end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thing %><br />
    <%= f.text_field :thing %>
  </div>
  <div class="field">
    <%= f.label :statusname %><br />
    <%= f.text_field :statusname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Edit status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to '<< Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Object statuses</h1>
<p>
<%= link_to 'Add a new status', new_status_path %>
</p>
<div class ="index_table">
<table>
  <tr>
    <th>Object</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  
  <tr>
    
    <td><%= status.thing %></td>
    <td><%= status.statusname %></td>
    <%if admin? then %>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>

  </tr>
<% end %>
</table>
</div>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to '<< Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<div class = "field">
  <b>Object:</b>
  
  <%= @status.thing %>
  </div>
</p>

<p>
  <div class = "field">
  <b>Status name:</b>
  <%= @status.statusname %>
  </div>
</p>



<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to '<< Back', statuses_path %>