config/routes.rb
GaSchedulerv3::Application.routes.draw do
  

  get "home/index"

  root to: 'home#index'

 

  get "/signup",    to: "profiles#new",      as: :signup
  get "/login",     to: "sessions#new",     as: :login
  delete "/logout", to: "sessions#destroy", as: :logout

  get "/profile", to: "profiles#edit", as: :my_profile

 
  resources :sessions, only: [:new, :create, :destroy]
 
  resources :locations

  resources :histories

  resources :classrooms

  resources :statuses

  resources :profiles

  resources :roles

  resources :tutorials

  resources :cohorts do 
    member do
      get :enroll
    end
  end

  resources :lessons

  resources :courses
 

 

   

end

app/models/ability.rb
class Ability
  include CanCan::Ability
     
  def initialize(user)

    user ||= Profile.new
    case user.role.name
    
      when "admin"
           can :manage, :all
      when "producer"
        can :manage, Cohort
        can [:update, :edit, :index], Profile
        can [:index, :show], Course
       when "instructor"
        can [:edit, :update], Profile
        can :manage, Cohort
       when "student"
        can [:edit, :update], Profile
        can [:index, :show, :enroll], Cohort
        when "teaching assistant"
        can [:edit, :update], Profile
        can :manage, Cohort
      end
    end
  end

#     if user.role.name == "admin"
#       can :manage, :all
#     end

#     if user.role.name == "producer"
#       can :edit, :new, :destory, Cohorts
#     end
#   end
# end
  
  

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :chairs, :chillout, :location_id, :name, :projector, :tables
  
  belongs_to :location
  has_many :tutorials

  validates :name, :location_id, presence: true
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :course_id, :end_date, :location_id, :name, :start_date, :status_id, :profile_ids
  belongs_to :course
  has_many :tutorials
  has_and_belongs_to_many :profiles
  belongs_to :status
  belongs_to :location



  validates :name, presence: true, uniqueness: true
  validates :profile_ids, presence: true
  
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :description, :name, :outcome, :status_id, :lesson_ids

has_and_belongs_to_many :lessons
belongs_to :status


 validates :name, presence: true, uniqueness: true

end

app/models/history.rb
class History < ActiveRecord::Base
  attr_accessible :c_id, :p_id, :st_id, :t_id
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :name, :status_id, :subject, :timerequired
  
  has_and_belongs_to_many :courses
  belongs_to :status

  validates :name, presence: true, uniqueness: true
  validates :subject, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  
  has_many :profiles
  has_many :classrooms
  has_many :tutorials
  has_many :cohorts

   validates :name, presence: true, uniqueness: true

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible  :name, :picture, :location_id, :role_id, :password, :email, :password_confirmation
  
  belongs_to :role
  has_and_belongs_to_many :cohorts
  has_and_belongs_to_many :tutorials
  belongs_to :location
  
  mount_uploader :picture, ProfileImageUploader
  
  has_secure_password
  
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
   has_many :profiles

  validates :name, presence: true, uniqueness: true
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :statusname, :thing

  has_many :courses
  has_many :lessons

 validates :statusname, presence: true, uniqueness: true
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  attr_accessible :cohort_id, :name, :status_id, :subject, :timerquired, :classroom_id, :location_id
    
    belongs_to :cohort
    belongs_to :classroom
    has_and_belongs_to_many :profiles
    belongs_to :status
    belongs_to :location
  
end

app/models/user.rb
class User < ActiveRecord::Base
   has_secure_password
  
  validates :email, presence: true, uniqueness: true
  attr_accessible :email, :password, :password_confirmation, :role
  belongs_to :profile


  def role?(role_to_test)
    self.role.to_s == role_to_test.to_s
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  # GET /tutorials
  # GET /tutorials.json
  before_filter :authenticate
  def index
    @tutorials = Tutorial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tutorials }
    end
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
    @tutorial = Tutorial.find(params[:id])
  

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tutorial }
    end
  end

  # GET /tutorials/new
  # GET /tutorials/new.json
  def new
    @tutorial = Tutorial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tutorial }
    end
  end

  # GET /tutorials/1/edit
  def edit
    @tutorial = Tutorial.find(params[:id])
  
    current_user_location_id = current_user.location_id
    @classrooms = Classroom.where(location_id: :current_user_location_id)
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = Tutorial.new(params[:tutorial])

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
        format.json { render json: @tutorial, status: :created, location: @tutorial }
      else
        format.html { render action: "new" }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tutorials/1
  # PUT /tutorials/1.json
  def update
    @tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      if @tutorial.update_attributes(params[:tutorial])
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.destroy

    respond_to do |format|
      format.html { redirect_to tutorials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  

  def admin?     
      current_user && current_user.role.name == "admin"
  end


end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tutorials/_form.html.erb
<%= form_for(@tutorial) do |f| %>
  <% if @tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% @tutorial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br />
    <%= f.collection_select :status_id, Status.where(thing: "tutorial"), :id, :statusname %>
  </div>
  <div class="field">
    <%= f.label :timerquired %><br />
    <%= f.number_field :timerquired %>
  </div>
  
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <% if admin? %>
   <div class="field">
 <%= f.label :location_id %><br />
    <%= f.collection_select :location_id, Location.all, :id, :name %>
</div>
<% end %>
<% if producer? %>
  <div class="field">
   Location <%= @tutorial.location.name %>
  </div>
<% end %>

     <div class="field">
    <%= f.label :classroom_id %><br />
    <%= f.collection_select :classroom_id, Classroom.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/tutorials/edit.html.erb
<h1>Editing tutorial</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<h1>Listing tutorials</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Duration</th>
    <th>Cohort</th>
    <th>Subject</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tutorials.each do |tutorial| %>
  <tr>
    <td><%= tutorial.name %></td>
    <td><%= tutorial.status.statusname %></td>
    <td><%= tutorial.timerquired %></td>
    <td><%= tutorial.cohort_id %></td>
    <td><%= tutorial.subject %></td>
    <td><%= tutorial.location.name %></td>
    <td><%= link_to 'Show', tutorial %></td>
    <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
    <td><%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tutorial', new_tutorial_path %>

app/views/tutorials/new.html.erb
<h1>New tutorial</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tutorial.name %>
</p>

<p>
  <b>Status:</b>
  <%= @tutorial.status.statusname %>
</p>

<p>
  <b>Timerquired:</b>
  <%= @tutorial.timerquired %>
</p>

<p>
  <b>Cohort:</b>
  <%= @tutorial.cohort_id %>
</p>

<p>
  <b>Subject:</b>
  <%= @tutorial.subject %>
</p>

  <b>Classroom:</b>
  <%= @tutorial.classroom.name %>
</p>

 <b>Location:</b>
  <%= @tutorial.location.name %>
</p>



 


<%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>